osx_image: xcode11.3
dist: trusty

language: node_js
node_js: '12'

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - osx
  - linux

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

script:
  - npm i
  - npm run release

branches:
  only:
    - master
