/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ActivityBar: typeof import('./src/components/sidebar/activityBar.vue')['default']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    Editor: typeof import('./src/components/editor/editor.vue')['default']
    Footer: typeof import('./src/components/sidebar/footer.vue')['default']
    Markdown: typeof import('./src/components/editor/markdown.vue')['default']
    Preview: typeof import('./src/components/editor/preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollBar: typeof import('./src/components/common/scrollBar.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/index.vue')['default']
    SignIn: typeof import('./src/components/sign/signIn.vue')['default']
    SignUp: typeof import('./src/components/sign/signUp.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon.vue')['default']
    TitleBar: typeof import('./src/components/titleBar.vue')['default']
    TocBar: typeof import('./src/components/sidebar/tocBar.vue')['default']
  }
}
